### ISSUE TITLE
no more watchlist / can't play any movies or series

### ISSUE THREAD

**Issue by dora71** [XLordKX/kodi#30]
Since yesterday (2015-09-15), Amazon seems to have changed URLs (again?).
I cannot access my watchlist (script error) and if I try to watch a video directly, it is the same script error. Didn't change anything in KODI itself, a new install didn't solve the problem.
However, I still can see covers and can navigate to films and series.

Here is the log:
14:04:11 T:2912212032   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.prime_instant/default.py", line 1423, in <module>
                                                playVideo(url, selectQuality=="true")
                                              File "/home/pi/.kodi/addons/plugin.video.prime_instant/default.py", line 738, in playVideo
                                                except: content = getUnicodePage(urlMainS+"/dp/"+videoID + "/?_encoding=UTF8")
                                              File "/home/pi/.kodi/addons/plugin.video.prime_instant/default.py", line 993, in getUnicodePage
                                                req = opener.open(url)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 439, in error
                                                result = self._call_chain(_args)
                                              File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
                                                result = func(_args)
                                              File "/usr/lib/python2.7/urllib2.py", line 626, in http_error_302
                                                return self.parent.open(new, timeout=req.timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 445, in error
                                                return self._call_chain(_args)
                                              File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
                                                result = func(_args)
                                              File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
14:04:11 T:3037990912   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.prime_instant/?url=B00ILIGMEG&mode=playVideo&name=Die+Unfassbaren+-+Now+You+See+Me&thumb=http%3A%2F%2Fecx.images-amazon.com%2Fimages%2FI%2F51ygAHE9l9L.jpg]

**Comment by TobiMob** [comment]
Same problem here.
Looks like Amazon returns a 404 error for the user agent string, used by the plugin  (:cry:) .

The addon has a file "default.py".
Line ~98 defines the user agent:

```
userAgent = "Mozilla/5.0 (X11; U; Linux i686; en-EN) AppleWebKit/533.4 (KHTML, like Gecko) Chrome/5.0.375.127 Large Screen Safari/533.4 GoogleTV/ 162671"
```

I changed mine to this:

```
userAgent = "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36"
```

It works for me now.
Could you please check if this also works for you?

**Comment by modkin** [comment]
I had the same Problem and this solution did work for me.

Thank you!

**Comment by oliver-fro** [comment]
Works for me, too.

Great Job!

**Comment by stefan-jung** [comment]
Works for me, too. (Linux/Arch)

**Comment by claell** [comment]
Can this get integrated into the addon, please?

**Comment by dora71** [comment]
OK, with the change of the user agent string, I now can access again my watchlists. I still have a buffering problem (which I had quite a time ago, but has disappeared for a long time now), but I will check that later on.
What I can say so far, that it is working again for me too. I am using kodi on a Raspberry Pi.

**Comment by Thandror** [comment]
I hope this fix will be integrated soon :)

**Comment by p-val** [comment]
Great! It works, thank you TobiMob... (pi2, osmc)

**Comment by cue108** [comment]
SolidRun - OpenElec 6 Beta
It works but buffering takes a very long time now!
Its like 3% buffering after 5 Minutes.

**Comment by c-MM** [comment]
Works for me too. (x86/debian/kodi 14.1)

**Comment by TobiMob** [comment]
#29 could fix this

**Comment by cue108** [comment]
Thanx TobiMob.
userAgentString from #29 did also fix the buffering thing for me.
"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0"

**Comment by XLordKX** [comment]
Going to fix it this evening. Thanks for providing a solution. :)
Am 17.09.2015 20:32 schrieb "cue108" notifications@github.com:

**Comment by OmaRichter** [comment]
Great work! Thanks a lot!

**Comment by claell** [comment]
@XLordKX Thanks

**Comment by tarator** [comment]
@XLordKX Great, thanks!

**Comment by walterheisenberg** [comment]
Again not working today (2015-09-29). Please have a look here:
http://www.kodinerds.net/index.php/Thread/43912-RELEASE-Amazon-Prime-Instant-Video-US-UK-DE/?postID=251506#post251506

The link to the video is created correctly, but Kodi can't play it.
