### ISSUE TITLE
Script failed! error again since 2 days

### ISSUE THREAD

**Issue by me-lina** [XLordKX/kodi#34]
Hello,

I'm getting the "Script failed!: Amazon Prime Instant Video" Error again since 2 days.

Heres the part of the log:

19:22:47 T:2885678144  NOTICE: Thread LanguageInvoker start, auto delete: false
19:22:47 T:2885678144  NOTICE: -->Python Interpreter Initialized<--
19:22:50 T:2885678144  NOTICE: https://www.amazon.de/dp/B00YYPKAVG/?_encoding=UTF8
19:22:52 T:2885678144  NOTICE: https://atv-ps-eu.amazon.com/cdp/catalog/GetASINDetails?version=2&format=json&asinlist=B00$
19:22:53 T:2885678144   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following$
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 410: Gone
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.prime_instant/default.py", line 14$
                                                playVideo(url, selectQuality=="true")
                                              File "/home/pi/.kodi/addons/plugin.video.prime_instant/default.py", line 78$
                                                asincontent = getUnicodePage('https://'+apiMain+'.amazon.com/cdp/catalog/$
                                              File "/home/pi/.kodi/addons/plugin.video.prime_instant/default.py", line 10$
                                                req = opener.open(url)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 445, in error
                                                return self._call_chain(_args)
                                              File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
                                                result = func(_args)
                                              File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 410: Gone
                                            -->End of Python script error report<--
19:22:53 T:3038289920   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.prime_instant/?u$
19:26:26 T:2885678144  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by robotniko** [comment]
Duplicate of https://github.com/XLordKX/kodi/issues/33
