### ISSUE TITLE
No items for listing in any category

### ISSUE THREAD

**Issue by laclaro** [XLordKX/kodi#35]
Hi,

some days before I noticed, that I cannot get any items in any category for listing. The plugin seems to run without exceptions, but no items are returned from amazon. Maybe they changed the api?

system: rpi, most recent OSMC system
version: rbp1-mediacenter-osmc 15.1.0-21
plugin: 1.7 (any)

Best regards,
Henning

**Comment by alex-marinov** [comment]
Same here. No items on any category listing, except my watchlist. The videos on my watchlist doesn't play, getting following error;
23:13:49 4035.911865 T:1540355104  NOTICE: https://www.amazon.co.uk/dp/B00EX62KOQ/?_encoding=UTF8
23:13:51 4037.212646 T:1540355104  NOTICE: https://atv-ps-eu.amazon.com/cdp/catalog/GetASINDetails?version=2&format=json&asinlist=B00EX62KOQ&deviceID=A7PB80N1VBLLA&includeRestrictions=true&deviceTypeID=A35LWR0L7KC0TJ&firmware=WIN%2017,0,0,188%20PlugIn&NumberOfResults=1
23:13:51 4037.464111 T:1540355104   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 410: Gone
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.prime_instant/default.py", line 1462, in <module>
                                                playVideo(url, selectQuality=="true")
                                              File "/home/osmc/.kodi/addons/plugin.video.prime_instant/default.py", line 785, in playVideo
                                                asincontent = getUnicodePage('https://'+apiMain+'.amazon.com/cdp/catalog/GetASINDetails?version=2&format=json&asinlist='+videoID+'&deviceID='+urllib.quote_plus(matchCID[0].encode("utf8"))+'&includeRestrictions=true&deviceTypeID='+matchDID[0]+'&firmware=WIN%2017,0,0,188%20PlugIn&NumberOfResults=1')
                                              File "/home/osmc/.kodi/addons/plugin.video.prime_instant/default.py", line 1010, in getUnicodePage
                                                req = opener.open(url)
                                              File "/usr/lib/python2.7/urllib2.py", line 437, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 475, in error
                                                return self._call_chain(_args)
                                              File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
                                                result = func(_args)
                                              File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 410: Gone
                                            -->End of Python script error report<--
23:13:51 4037.500732 T:1958265392   DEBUG: ------ Window Init (DialogKaiToast.xml) ------

**Comment by stopmuckingabout** [comment]
same as above. removed and replaced plugin but still get the same issue.

**Comment by wjanes** [comment]
See the other issues. The Links doesnt work anymore because of HTML5 Upgrade from Amazon.

**Comment by lassepe** [comment]
+1

**Comment by michael-gillett** [comment]
Currently facing the same issue.

**Comment by bruxi** [comment]
I have the same problem. Addon seems to work ok, no errors in the log file but the lists are all empty.

**Comment by ghost** [comment]
Has anyone had any luck with this issue? I was excited to get my new Prime account setup and I found that several other users are having the same issue I'm having.

**Comment by bruxi** [comment]
It's still the same issue. Will there be any activity in fixing this? Would be great to use Amazon Prime again in kodi.

**Comment by kaigame** [comment]
Having the same issue here, nothing in the log to suggest there is a problem

**Comment by negesti** [comment]
Since Amazon switched to HTML5 streaming and has not updated/published the full API. This addon does not work at the moment. See @XLordKX 's [comment](https://github.com/XLordKX/kodi/issues/33#issuecomment-146983739)

**Comment by kaigame** [comment]
fair enough, i'll wait then

**Comment by claell** [comment]
Probably you will have to wait for a long time (over a year).

**Comment by kaigame** [comment]
Well, thats no fun

**Comment by florianjacob** [comment]
@negesti Thanks for the info! Didn't find XLordKX's comment hidden in that other thread.
