### ISSUE TITLE
Logon Failed

### ISSUE THREAD

**Issue by TA2k** [XLordKX/kodi#36]
Since 3 days no Logon is possible. Login form looks and amazon.de/gp/sign-in.html looks still valid

**Comment by florianjacob** [comment]
I just installed the plugin on kodi 15.2 / OpenELEC 6.0.0 on a Raspberry Pi B, and I also can't login.

I found this error in the log files:

```
22:51:07 1205.745239 T:1562371136  NOTICE: https://www.amazon.de
22:51:08 1207.438843 T:1967448064   ERROR: GetDirectory - Error getting plugin://plugin.video.prime_instant/
22:51:08 1207.442139 T:1967448064   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.prime_instant/) failed
22:51:08 1207.471069 T:1562371136  NOTICE: Thread BackgroundLoader start, auto delete: false
22:51:23 1222.301025 T:1562371136  NOTICE: Thread LanguageInvoker start, auto delete: false
22:51:23 1222.636230 T:1562371136  NOTICE: -->Python Interpreter Initialized<--
22:51:27 1225.799438 T:1562371136  NOTICE: https://www.amazon.de
22:51:34 1233.698364 T:1562371136   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.prime_instant/default.py", line 1499, in <module>
                                                index()
                                              File "/storage/.kodi/addons/plugin.video.prime_instant/default.py", line 107, in index
                                                loginResult = login()
                                              File "/storage/.kodi/addons/plugin.video.prime_instant/default.py", line 1124, in login
                                                elif signoutmatch[0].strip() != "null":
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
22:51:35 1233.983398 T:1967448064   ERROR: GetDirectory - Error getting plugin://plugin.video.prime_instant/
22:51:35 1233.986938 T:1967448064   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.prime_instant/) failed
```

**Comment by zioalex** [comment]
I have the same problem with OpenElec 6.0.3 . Any update here?

**Comment by florianjacob** [comment]
@zioalex: no, see https://github.com/XLordKX/kodi/issues/33#issuecomment-146983739 - in short, the amazon API has changed fundamentally but the specs are not published (yet, if that will ever be the case).

**Comment by zioalex** [comment]
Thanks @florianjacob Let's see.

**Comment by claell** [comment]
There is already a working solution for Kodi 17 I think.

**Comment by zioalex** [comment]
Hi Claudius, please can you point to that?

**Comment by claell** [comment]
This should be the thread, but it is in German: http://www.kodinerds.net/index.php/Thread/44211-Release-Amazon-Prime-Instant-Video/?pageNo=1 There might also be other solutions available.

**Comment by oomek** [comment]
Every time I enter my login details a message pops up to check my credentials. In the library instead of Amazon videos I see my local files from HDD. Is this plugin even functional? Kodi 16.1 / Windows

**Comment by CaptainMegane** [comment]
I have problems with login, too. German  Amazon User. When will a fix be available?

**Comment by robsdedude** [comment]
Confirm this. Same error in the log file.

Question: If the Amazon API has changed and this plugin isn't working anymore: Why isn't there a hint on this issue in the description. Or alternatively why don't you take that plugin down? Would have saved me like 30 minutes of my life. (Don't get me wrong: I appreciate the work you did).

**Comment by billmcilhargey** [comment]
Can't login with US user either

**Comment by Howsyomamanem** [comment]
Login not working for me either.

**Comment by eckirchn** [comment]
Unable to login either, in the US, using 2-factor but appending code to end of password like a desktop.  From my logfile:

20:34:39 945466.875000 T:1956570032   ERROR: GetDirectory - Error getting plugin://plugin.video.prime_instant/
20:34:39 945466.875000 T:1956570032   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.prime_instant/) failed
20:34:49 945477.250000 T:1956570032   ERROR: GetDirectory - Error getting addons://sources/
20:34:49 945477.250000 T:1956570032   ERROR: CGUIMediaWindow::GetDirectory(addons://sources/) failed

**Comment by boospy** [comment]
Problem exists:

```
19:32:35.508 T:139866183649344   ERROR: GetDirectory - Error getting plugin://plugin.video.prime_instant/
19:32:35.510 T:139866183649344   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.prime_instant/) failed
19:33:17.566 T:139866183649344   ERROR: Control 52 in window 10025 has been asked to focus, but it can't
19:33:36.495 T:139863395399424   ERROR: GetDirectory - Error getting
19:34:24.710 T:139866183649344   ERROR: GetDirectory - Error getting plugin://plugin.video.prime_instant/
19:34:24.712 T:139866183649344   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.prime_instant/) failed
```

**Comment by ghost** [comment]
I can play videos but I get a login error each time and I can't view my video library
```
23:25:37.634 T:123145371996160   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/Users/snowcrash/Library/Application Support/Kodi/addons/plugin.video.prime_instant/default.py", line 1499, in <module>
                                                index()
                                              File "/Users/snowcrash/Library/Application Support/Kodi/addons/plugin.video.prime_instant/default.py", line 107, in index
                                                loginResult = login()
                                              File "/Users/snowcrash/Library/Application Support/Kodi/addons/plugin.video.prime_instant/default.py", line 1124, in login
                                                elif signoutmatch[0].strip() != "null":
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
```

**Comment by eightsixeight** [comment]
is this project dead ?
